mutation saveAnswers($input: [GivenAnswerInput!]!) {
    saveAnswers(answers: $input)
}

mutation getWords($mode: String!) {
    getWords(mode: $mode) {
        word {
            id
            definition_en
            word_en
            word_pl
            examples
            base_word_en,
            other_forms,
        }
        similarEnWords
        similarPlWords
        learnEntries {
            correct
            date
            mode
            language
            session {
                mode
            }
        }
    }
}
